server:
  port: "8000"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "your_password"
  dbname: "car_dealership"
  sslmode: "disable"

jwt:
  secret: "your_jwt_secret" 
  ttl: "24h"


app: 
  environment: "development"
  log_level: "debug"