version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dealership
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      migrate -path=/migrations -database=postgres://postgres:postgres@db:5432/dealership?sslmode=disable up
      "
    restart: on-failure

  app:
    build: .
    depends_on:
      - db
      - migrate
    ports:
      - "8000:8000"
    environment:
      DB_DSN: "postgres://postgres:postgres@db:5432/dealership?sslmode=disable"

volumes:
  pgdata:
